name: ami_actions
run-name: Build AMI by Packer By @${{ github.actor }}
on:
  push:
    branches: [main]

jobs:
  packer_build:
    env:
      go-version: 1.21

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set Go ${{ env.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.go-version }}

      - name: Display Go version
        run: go version

      - name: Build
        run: sh build.sh

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "1.8.3"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Packer Init
        run: packer init .

      - name: Build AMI
        run: packer build .